### ISSUE TITLE
deparam() requires lowercase input

### ISSUE THREAD

**Issue by mherdeg** [seomoz/url-py#25]
deparam() extracts parameter names and coerces them to lowercase, then compares them against the the list of input parameters it was passed.

If an input parameter is not lowercase, it will effectively be skipped in deparam() logic (it will never match an extracted param name).

    print url.parse("http://example.com/?name=test").deparam("name")
    http://example.com/

    print url.parse("http://example.com/?NAME=test").deparam("NAME")
    http://example.com/?NAME=test

    print url.parse("http://example.com/?NaME=test").deparam("name")
    http://example.com/

I was surprised by this in "real life" when I tried to use this library to remove the parameter "CID" from a query string and took a couple of minutes to figure out why it was having no effect. I just worked around with

    params = args.params.lower().split(",")

This behavior is perfectly reasonable; can it please be documented so it doesn't trip folks up?

**Comment by b4hand** [comment]
I think I'd probably rather incorporate the lower call into `deparam`. I'd still make sure the documentation for `deparam` made it clear that the argument was case insensitive.

**Comment by dlecocq** [comment]
I would also be happy with incorporating lower into `deparam`.

**Comment by b4hand** [comment]
Fixed by #27.
