### ISSUE TITLE
Update the publicsuffix list (or fork it?)

### ISSUE THREAD

**Issue by pombredanne** [seomoz/url-py#29]
publicsuffix provides a list that is about 1.5 year old and does not seem to be much maintained with no git activity for about the same time: https://www.tablix.org/~avian/git/publicsuffix.git/

**Comment by pombredanne** [comment]
I forked it here https://github.com/pombredanne/python-publicsuffix2
And published on Pypi. Essentially the same code with the same API and same module name but with an updated layout, pep8 and public suffix list.

**Comment by smeinecke** [comment]
Main problem is that the module "publicsuffix" is shipped by default with a very outdated version of the mozilla public suffix list. 
We could either switch to another library which does the download itself or at least it should be possible to define a local copy of the list instead of the shipped version.

**Comment by pombredanne** [comment]
@smeinecke The latest `publicsuffix` has a fetch function: see https://www.tablix.org/~avian/git/#publicsuffix
I publish a fork as Pypi `publicsuffix2` but I did not keep that as updated as I would like.

**Comment by smeinecke** [comment]
@pombredanne it seems that the latest version of the `publicsuffix` module also fail to parse the current mozilla file (at least it does this on my local install).

**Comment by dlecocq** [comment]
Many folks will want to be able to use latest and greatest PSL, but some applications are very sensitive to the list and need to keep the version pinned. (As it happens, we have a small handful of such applications.)

Whatever we pursue, I'd like to be able to provide a reasonably-recent default with the option to use a specific file.

**Comment by dlecocq** [comment]
This should now be resolved by #45 . It both introduces a PSL update and a mechanism to supply your own PSL.
