### ISSUE TITLE
`pip install url` fails

### ISSUE THREAD

**Issue by mathieulongtin** [seomoz/url-py#48]
It worked fine yesterday (url==0.2.0) and it fails horribly this morning:

[mathieu_longtin@unv-mlongtin02 ~]$ pip install url -U
Collecting url
  Using cached url-0.3.0.tar.gz
Requirement already up-to-date: six in /.local/work/mlongtin/py2712/lib/python2.7/site-packages (from url)
Building wheels for collected packages: url
  Running setup.py bdist_wheel for url ... error
  Complete output from command /.local/work/mlongtin/py2712/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6KW_wy/url/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpQ9V847pip-wheel- --python-tag cp27:
  Building from Cython
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/url
  copying url/__init__.py -> build/lib.linux-x86_64-2.7/url
  creating build/lib.linux-x86_64-2.7/url/psl
  copying url/psl/2016-08-16.psl -> build/lib.linux-x86_64-2.7/url/psl
  running build_ext
  cythoning url/url.pyx to url/url.cpp
  error: [Errno 2] No such file or directory: '/tmp/pip-build-6KW_wy/url/url/url.pyx'

  ----------------------------------------
  Failed building wheel for url
  Running setup.py clean for url
Failed to build url
Installing collected packages: url
  Found existing installation: url 0.2.0
    Uninstalling url-0.2.0:
      Successfully uninstalled url-0.2.0
  Running setup.py install for url ... error
    Complete output from command /.local/work/mlongtin/py2712/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6KW_wy/url/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ptwjId-record/install-record.txt --single-version-externally-managed --compile --install-headers /.local/work/mlongtin/py2712/include/site/python2.7/url:
    Building from Cython
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/url
    copying url/__init__.py -> build/lib.linux-x86_64-2.7/url
    creating build/lib.linux-x86_64-2.7/url/psl
    copying url/psl/2016-08-16.psl -> build/lib.linux-x86_64-2.7/url/psl
    running build_ext
    cythoning url/url.pyx to url/url.cpp
    error: [Errno 2] No such file or directory: '/tmp/pip-build-6KW_wy/url/url/url.pyx'

    ----------------------------------------
  Rolling back uninstall of url
Command "/.local/work/mlongtin/py2712/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6KW_wy/url/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ptwjId-record/install-record.txt --single-version-externally-managed --compile --install-headers /.local/work/mlongtin/py2712/include/site/python2.7/url" failed with error code 1 in /tmp/pip-build-6KW_wy/url/

**Comment by dlecocq** [comment]
Thanks for the report! The issue was that `url/url.pxd` and `url/url.pyx` weren't added to the manifest, so building from Cython doesn't work in the `0.3.0` release. It's something that we could have caught with `0.3.0rc1` or `0.3.0rc2`, but apparently did not.

I'll be pushing a PR for `0.3.1` and releasing it when it's merged. In the mean time, you could keep your version pinned to `0.2.0`, but I expect it will be fixed on the latest release later today.

The upside of `0.3.1` over `0.2.0` will be a 30-40x performance bump, though, so there's the silver lining to look forward to!

**Comment by dlecocq** [comment]
Should be resolved now with the release of `0.3.1`.

**Comment by mathieulongtin** [comment]
That worked, thanks! The only reason I noticed is because nsq-py has a dependency on it.
